quarkus:
  http:
    port: 9000

  datasource:
    db-kind: h2
    username: sa
    password: password
    jdbc:
      url: jdbc:h2:mem:test

  hibernate-orm:
    dialect: org.hibernate.dialect.H2Dialect
    database:
      generation: drop-and-create
    sql-load-script:  import.sql
    log:
      sql: false

  rest-client:
    pokemon:
      url: https://pokeapi.co/api/v2/pokemon/

  native:
    resources:
      includes: sql/*.sql
    additional-build-args: -H:ResourceConfigurationFiles=resources-config.json

    quarkus:
      smallrye-openapi:
        path: /swagger
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"